config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :teams

  resources :groups do
    collection do
      post :play_off_generate
      post :final_generate
    end
  end

  delete 'erase_db', to: 'erase#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :matches, dependent: :destroy
  has_and_belongs_to_many :teams

  scope :final,         -> { where(title: "final") }
  scope :half_final,    -> { where(title: "1_2") }
  scope :quarter_final, -> { where(title: "1_4") }
  scope :play_off,      -> { where(title: "play_off") }
end

app/models/match.rb
class Match < ApplicationRecord
  has_many :team_scores, dependent: :destroy
  has_many :teams, through: :team_scores
  belongs_to :group
end

app/models/team.rb
class Team < ApplicationRecord
  EXPECTED_TEAMS_COUNT = 16

  has_many :team_scores, dependent: :destroy
  has_many :matches, through: :team_scores
  has_and_belongs_to_many :groups

  validates :title, presence: true, uniqueness: true
end

app/models/team_score.rb
class TeamScore < ApplicationRecord
  belongs_to :team
  belongs_to :match
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/erase_controller.rb
class EraseController < ApplicationController
  def destroy
    ApplicationRecord.transaction do
      Team.all.each(&:destroy!)
      Group.all.each(&:destroy!)
      Match.all.each(&:destroy!)
    end
    redirect_to root_path flash[:notice] = "All Games Teams and Matches was destroyed"
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :check_teams_count, only: :create
  before_action :check_groups_count, only: :play_off_generate
  before_action :check_play_off, only: :final_generate

  def create
    GroupsGeneratorService.new.call
    redirect_to root_path flash[:notice] = "#{Group.count} groups was created"
  end

  def play_off_generate
    PlayOffGeneratorService.new.call
    redirect_to root_path flash[:notice] = "#Play off groups was created"
  end

  def final_generate
    3.times do FinalGeneratorService.new.call end
    redirect_to root_path flash[:notice] = "Final matches was created"
  end

  private

  def check_teams_count
    if Team.count != Team::EXPECTED_TEAMS_COUNT
      flash[:error] = "You don't have enough teams"
      redirect_to root_path
    end
  end

  def check_groups_count
    unless Group.any?
      flash[:error] = "You don't have enough groups"
      redirect_to root_path
    end
  end

  def check_play_off
    unless Group.where(title: "play_off").any?
      flash[:error] = "First generate play off"
      redirect_to root_path
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :check_teams_count, only: :create
  def create
    service = TeamsGeneratorService.new
    if service.call
      redirect_to root_path flash[:notice] = "#{Team::EXPECTED_TEAMS_COUNT} teams was created"
    else
      redirect_to root_path flash[:notice] = "Something got wrong... Teams with this title has been already created"
    end
  end
  private
  def check_teams_count
    if Team.count == Team::EXPECTED_TEAMS_COUNT
      flash[:notice] = "You have enough teams for tournament"
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @teams = Team.all
    @groups = Group.all
    @matches = Match.all
    @group_matches = @matches.first(56)
    @group_matches_first_half = @group_matches.first(28)
    @group_matches_last_half = @group_matches.last(28)
    @group_a_teams = Team.joins(:groups).includes(:team_scores).where(groups: {title: 'A'})
    @group_b_teams = Team.joins(:groups).includes(:team_scores).where(groups: {title: 'B'})

    @play_off_matches = @matches.where(group_id: Group.play_off)
    @_1_4_matches =  @matches.where(group_id: Group.quarter_final)
    @_1_2_matches =  @matches.where(group_id: Group.half_final)
    @final_matches =  @matches.where(group_id: Group.final)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testtask</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 style="font-size: 100px; color: red;">НУРС ПИДОР!!!</h1>
    <%= render 'shared/navbar' %>
    <%= render 'shared/message' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert', 'error').gsub('notice','success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Mogo</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Generate Teams', teams_path, method: :post %></li>
            <li><%= link_to 'Generate Groups', groups_path, method: :post %></li>
            <li><%= link_to 'Generate Play Off', play_off_generate_groups_path, method: :post %></li>
            <li><%= link_to 'Generate Final', final_generate_groups_path, method: :post %></li>
            <li><%= link_to 'Erase DB', erase_db_path, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
            <li class="active"><a href="./">Static top <span class="sr-only">(current)</span></a></li>
            <li><a href="../navbar-fixed-top/">Fixed top</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/welcome/index.html.erb
<h1>Teams</h1>
<div class="row">
  <div class="col col-lg-6">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Title</th>
          <th scope="col">Group</th>
        </tr>
      </thead>
      <% @teams.first(8).each do |team| %>
      <tbody>
        <tr>
          <th scope="row"><%= team.id %></th>
          <td><%= team.title %></td>
          <td><%= team.groups.first.title if Group.any? %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
  <div class="col col-lg-6">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Title</th>
          <th scope="col">Group</th>
        </tr>
      </thead>
      <% @teams.last(8).each do |team| %>
      <tbody>
        <tr>
          <th scope="row"><%= team.id %></th>
          <td><%= team.title %></td>
          <td><%= team.groups.first.title if Group.any? %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
</div>

<h1>Matches</h1>
<div class="row matches">
  <div class="col col-lg-3">
    <table class="table table-sm">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Group</th>
          <th scope="col">Team pair</th>
          <th scope="col">Score</th>
        </tr>
      </thead>
      <% @group_matches_first_half.first(14).each do |match| %>
      <tbody>
        <tr>
          <th scope="row"><%= match.id %></th>
          <td><%= match.group.title %></td>
          <td><%= match.team_scores.first.team.title %> - <%= match.team_scores.last.team.title %></td>
          <td><%= match.team_scores.first.score %> - <%= match.team_scores.last.score %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
  <div class="col col-lg-3">
    <table class="table table-sm">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Group</th>
          <th scope="col">Team pair</th>
          <th scope="col">Score</th>
        </tr>
      </thead>
      <% @group_matches_first_half.last(14).each do |match| %>
      <tbody>
        <tr>
          <th scope="row"><%= match.id %></th>
          <td><%= match.group.title %></td>
          <td><%= match.team_scores.first.team.title %> - <%= match.team_scores.last.team.title %></td>
          <td><%= match.team_scores.first.score %> - <%= match.team_scores.last.score %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
  <div class="col col-lg-3">
    <table class="table table-sm">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Group</th>
          <th scope="col">Team pair</th>
          <th scope="col">Score</th>
        </tr>
      </thead>
      <% @group_matches_last_half.first(14).each do |match| %>
      <tbody>
        <tr>
          <th scope="row"><%= match.id %></th>
          <td><%= match.group.title %></td>
          <td><%= match.team_scores.first.team.title %> - <%= match.team_scores.last.team.title %></td>
          <td><%= match.team_scores.first.score %> - <%= match.team_scores.last.score %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
  <div class="col col-lg-3">
    <table class="table table-sm">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Group</th>
          <th scope="col">Team pair</th>
          <th scope="col">Score</th>
        </tr>
      </thead>
      <% @group_matches_last_half.last(14).each do |match| %>
      <tbody>
        <tr>
          <th scope="row"><%= match.id %></th>
          <td><%= match.group.title %></td>
          <td><%= match.team_scores.first.team.title %> - <%= match.team_scores.last.team.title %></td>
          <td><%= match.team_scores.first.score %> - <%= match.team_scores.last.score %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
</div>

<h1>Group Results</h1>
<div class="row">
  <div class="col col-lg-6">
    <table class="table table-sm">
      <thead>
        <tr>
          <th scope="col">Team</th>
          <th scope="col">Team Score</th>
        </tr>
      </thead>
      <% @group_a_teams.each do |team| %>
      <tbody>
        <tr>
          <td><%= team.title %></td>
          <td><%= team.team_scores.sum(:score) %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
  <div class="col col-lg-6">
    <table class="table table-sm">
      <thead>
        <tr>
          <th scope="col">Team</th>
          <th scope="col">Team Score</th>
        </tr>
      </thead>
      <% @group_b_teams.each do |team| %>
      <tbody>
        <tr>
          <td><%= team.title %></td>
          <td><%= team.team_scores.sum(:score) %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
</div>


<h1>Play Off</h1>

<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Group</th>
      <th scope="col">Team 1</th>
      <th scope="col">Team Ol'scores</th>
      <th scope="col">Team 1 Score</th>
      <th scope="col">Team 2</th>
      <th scope="col">Team 2 Score</th>
    </tr>
  </thead>
  <% @play_off_matches.each do |match| %>
  <tbody>
    <tr>
      <th scope="row"><%= match.id %></th>
      <td><%= match.group.title %></td>
      <td><%= match.team_scores.first.team.title %></td>
      <td><%= match.team_scores.first.score %></td>
      <td><%= match.team_scores.last.team.title %></td>
      <td><%= match.team_scores.last.score %></td>
    </tr>
  </tbody>
  <% end %>
</table>
<%- if @_1_4_matches %>
  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Group</th>
        <th scope="col">Team 1</th>
        <th scope="col">Team Ol'scores</th>
        <th scope="col">Team 1 Score</th>
        <th scope="col">Team 2</th>
        <th scope="col">Team 2 Score</th>
      </tr>
    </thead>
    <% @_1_4_matches.each do |match| %>
    <tbody>
      <tr>
        <th scope="row"><%= match.id %></th>
        <td><%= match.group.title %></td>
        <td><%= match.team_scores.first.team.title %></td>
        <td><%= match.team_scores.first.score %></td>
        <td><%= match.team_scores.last.team.title %></td>
        <td><%= match.team_scores.last.score %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
<% end %>

<%- if @_1_2_matches %>
  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Group</th>
        <th scope="col">Team 1</th>
        <th scope="col">Team Ol'scores</th>
        <th scope="col">Team 1 Score</th>
        <th scope="col">Team 2</th>
        <th scope="col">Team 2 Score</th>
      </tr>
    </thead>
    <% @_1_2_matches.each do |match| %>
    <tbody>
      <tr>
        <th scope="row"><%= match.id %></th>
        <td><%= match.group.title %></td>
        <td><%= match.team_scores.first.team.title %></td>
        <td><%= match.team_scores.first.score %></td>
        <td><%= match.team_scores.last.team.title %></td>
        <td><%= match.team_scores.last.score %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
<% end %>

<%- if @final_matches %>
  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Group</th>
        <th scope="col">WINNER</th>
      </tr>
    </thead>
    <% @final_matches.each do |match| %>
    <tbody>
      <tr>
        <th scope="row"><%= match.id %></th>
        <td><%= match.group.title %></td>
        <td><%= match.team_scores.first.team.title %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
<% end %>